In [58]:
import pandas as pd
import numpy as np

In [59]:
df=pd.read_csv('/content/Reddit_Data.csv')
df

clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37244                                              jesus         0
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[37249 rows x 2 columns]

In [60]:
x=df['clean_comment']
y=df['category']

In [61]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(x.apply(lambda x:np.str_(x)))

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42)

In [63]:
# logistic Regression

In [64]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0)
lr.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [65]:
y_pred = lr.predict(x_test)
y_pred

array([ 0,  0,  1, ...,  0, -1, -1])

In [66]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [67]:
confusion_matrix(y_pred,y_test)

array([[1630,   45,  228],
       [ 191, 3146,  193],
       [ 273,   55, 3552]])

In [68]:
accuracy_score(y_pred,y_test)

0.8942338666380328

In [69]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

          -1       0.78      0.86      0.82      1903
           0       0.97      0.89      0.93      3530
           1       0.89      0.92      0.90      3880

    accuracy                           0.89      9313
   macro avg       0.88      0.89      0.88      9313
weighted avg       0.90      0.89      0.90      9313



In [70]:
# Decision Classifier

In [71]:
from sklearn.tree import DecisionTreeClassifier
dc = DecisionTreeClassifier(random_state=0)

In [72]:
dc.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [73]:
y_pred = dc.predict(x_test)
y_pred

array([ 0,  0,  1, ...,  0, -1, -1])

In [74]:
confusion_matrix(y_pred,y_test)

array([[1179,  122,  553],
       [ 288, 2934,  346],
       [ 627,  190, 3074]])

In [75]:
accuracy_score(y_pred,y_test)

0.7717169547943734

In [76]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

          -1       0.56      0.64      0.60      1854
           0       0.90      0.82      0.86      3568
           1       0.77      0.79      0.78      3891

    accuracy                           0.77      9313
   macro avg       0.75      0.75      0.75      9313
weighted avg       0.78      0.77      0.78      9313

